/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProjectsForm.java
 *
 * Created on 8.12.2011, 15:15:44
 */
package nextQuest.guiClient;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import nextQuest.ifc.iUserManagerAdmin;
import nextQuest.ifc.nqException;
import nextQuest.mock.ProjectManagerMock;
import nextQuest.server.Project;
import nextQuest.server.UserInfo;

/**
 *
 * @author Obik
 */
public class ProjectsForm extends javax.swing.JDialog  {
Frame parent;
    ProjectManagerMock pm = null;
    Project projInf = null;
    iUserManagerAdmin uma=null;
    ArrayList<UserInfo> usrInf2 = new ArrayList<UserInfo>();
    /** Creates new form ProjectsForm */
    public ProjectsForm(java.awt.Frame parent, ProjectManagerMock pm, Project projInf,iUserManagerAdmin uma) throws RemoteException, nqException {
        super(parent,true);
        this.parent = parent;
        this.pm = pm;
        this.projInf = projInf;
        this.uma=uma;
        initComponents();
        initializeRow(); 
        if(projInf != null) {
            t_name.setText(projInf.getName());
            t_priority.setText(Integer.toString(projInf.getPriority()));
            if(projInf.getLeader()!=null){
            ChLeader.select(projInf.getLeader().getName());
            }
        }
        
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screen.width / 2 - getWidth() / 2, screen.height / 2 - getHeight() / 2);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_priority = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        b_save = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        ChLeader = new java.awt.Choice();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Project form");
        setMinimumSize(new java.awt.Dimension(297, 377));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);

        jLabel1.setText("Name:");

        t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nameActionPerformed(evt);
            }
        });
        t_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nameKeyTyped(evt);
            }
        });

        jLabel2.setText("Priority:");

        t_priority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_priorityActionPerformed(evt);
            }
        });
        t_priority.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_priorityKeyTyped(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setText("Comment:");

        b_save.setText("Save");
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });

        b_cancel.setText("Cancel");
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        ChLeader.setName("ChLeader"); // NOI18N

        jLabel5.setText("Leader:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_priority, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(t_name, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)))
                    .addComponent(ChLeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_save)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_priority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addComponent(ChLeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_save)
                    .addComponent(b_cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ChLeader.getAccessibleContext().setAccessibleName("ChLeader");
    }// </editor-fold>//GEN-END:initComponents

private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
dispose();
}//GEN-LAST:event_b_cancelActionPerformed

private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
      //splitDate("11.04.2005");
    System.out.println();
    if(t_name.getText().length() < 3 || t_name.getText().length() > 40) {
                JOptionPane.showMessageDialog(null, "Length of a name must be between 3 and 40 characters...", "Input error", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (t_priority.getText().length() < 1 || t_priority.getText().length() > 5) {
                JOptionPane.showMessageDialog(null, "Length of a priority must be between 1 and 5 numbers...", "Input error", JOptionPane.ERROR_MESSAGE);
                return;
            } else if(!isNumeric(t_priority.getText())){
              JOptionPane.showMessageDialog(null, "Priority must be number.", "Input error", JOptionPane.ERROR_MESSAGE);
                return;  
            }else if(ChLeader.getSelectedIndex()==-1){
              JOptionPane.showMessageDialog(null, "Create an Leader", "Input error", JOptionPane.ERROR_MESSAGE);
                return;  
            }
     if(projInf != null) {
         pm.editProject(projInf, t_name.getText(), usrInf2.get(ChLeader.getSelectedIndex()),Integer.valueOf(t_priority.getText()));
     }else{
        try {
            pm.createProject(t_name.getText(), usrInf2.get(ChLeader.getSelectedIndex()),Integer.valueOf(t_priority.getText()));
        } catch (nqException ex) {
            Logger.getLogger(ProjectsForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ProjectsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
  dispose();
        
}//GEN-LAST:event_b_saveActionPerformed

private void t_priorityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_priorityKeyTyped
// TODO add your handling code here:
}//GEN-LAST:event_t_priorityKeyTyped

private void t_priorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_priorityActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_t_priorityActionPerformed

private void t_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nameKeyTyped
       
}//GEN-LAST:event_t_nameKeyTyped

private void t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t_nameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice ChLeader;
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_priority;
    // End of variables declaration//GEN-END:variables
        public boolean isNumeric(String input){  
       try{  
          Integer.valueOf(input);
          return true;  
       }catch(Exception zht){  
          return false;  
       }  
    }  
        private void initializeRow() throws RemoteException, nqException {
        UserInfo usrInf[] = uma.listAllUsers();
        for (UserInfo info : usrInf) {
                if(info.getPermissionLeader()){
                  usrInf2.add(info);  
                }
            }
            for (UserInfo info : usrInf2) {
                ChLeader.addItem(info.getName());
            }
    }
                public boolean splitDate(String input){  //zbytecne nedokoncene
                    String dd,mm,yy;
                    int idd,imm,iyy;
       try{  
          dd=input.substring(0, 2);
          if(isNumeric(dd)){
          idd=Integer.valueOf(dd);
              System.out.println(idd);
              System.out.println(input);
          }else{
              
          }
          mm=input.substring(3, 5);
          if(isNumeric(mm)){
          imm=Integer.valueOf(mm);
              System.out.println(imm);
          }else{
           
       }
          yy=input.substring(6, 10);
          if(isNumeric(yy)){
          iyy=Integer.valueOf(yy);
              System.out.println(iyy);
          }else{
          
       }
          return true;  
       }catch(Exception zht){  
          return false;  
       }  
    }  
}