package nextQuest.guiClient;

public class QuestsRow extends javax.swing.JPanel {

    /** Creates new form QuestsRow */
    public QuestsRow(String name, String decription, int progress) {
        initComponents();
        l_name.setText(name);
        l_decription.setText(decription);
        this.progress.setValue(progress);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_name = new javax.swing.JLabel();
        l_decription = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();

        l_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_name.setText("Name");

        l_decription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        l_decription.setText("<html>Description asdf asdf asdfasdfasdf asdaf asd fasf asf as fas f</html>");
        l_decription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        l_decription.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        l_decription.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        progress.setOrientation(1);
        progress.setToolTipText("Progress");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_name)
                        .addGap(182, 182, 182))
                    .addComponent(l_decription, 0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(l_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_decription, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l_decription;
    private javax.swing.JLabel l_name;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables

}
