/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuestsPanel.java
 *
 * Created on 18.11.2011, 15:57:15
 */

package nextQuest.guiClient;

import java.awt.Color;
import java.awt.TextField;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JSplitPane;
import javax.swing.SwingConstants;
import nextQuest.ifc.iTask;
import nextQuest.ifc.nqException;

/**
 *
 * @author Tomas
 */
public class QuestsPanel extends javax.swing.JPanel {
    iTask [] quests;

    /** Creates new form QuestsPanel */
    public QuestsPanel() {
        initComponents();
    }

    public void update(iTask [] quests) {
        this.quests = quests;
        update();
    }

    private void update() {
        removeAll();
        JLabel name, description;
        JProgressBar progress;
        for (iTask task : quests) {
            name = new JLabel(/*task.getName()*/"name");
            name.setForeground(Color.red);
            add(name);

            try {
                description = new JLabel(task.getDescription());
                description.setForeground(Color.blue);
                add(description);
            } catch (RemoteException ex) {
                Logger.getLogger(QuestsPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (nqException ex) {
                Logger.getLogger(QuestsPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            progress = new JProgressBar(SwingConstants.VERTICAL);
            progress.setValue(50/*value*/);
            add(progress);

            add(new JSplitPane());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
